"""update_addRegionsToChurches

Revision ID: 3e0d9111b21d
Revises: bae253e116ab
Create Date: 2025-09-20 18:52:20.476862

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e0d9111b21d'
down_revision = 'bae253e116ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('churches', schema=None) as batch_op:
        batch_op.add_column(sa.Column('region', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('churches', schema=None) as batch_op:
        batch_op.drop_column('region')

    # ### end Alembic commands ###
