"""alter_addcampidtopayments

Revision ID: 42194705610f
Revises: b07cc90a6c81
Create Date: 2025-08-22 00:01:14.637427

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '42194705610f'
down_revision = 'b07cc90a6c81'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('camp_id', sa.String(length=36), nullable=False))
        batch_op.create_foreign_key(batch_op.f('fk_payments_camp_id_camps'), 'camps', ['camp_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_payments_camp_id_camps'), type_='foreignkey')
        batch_op.drop_column('camp_id')

    # ### end Alembic commands ###
