"""form description to registration link

Revision ID: 429a09c34ba2
Revises: c6e7b1230cef
Create Date: 2025-08-18 13:32:34.397845

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '429a09c34ba2'
down_revision = 'c6e7b1230cef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('churches', schema=None) as batch_op:
        batch_op.create_unique_constraint('church_name_district_area_camp_id_unique', ['name', 'district', 'area', 'camp_id'])

    with op.batch_alter_table('registration_links', schema=None) as batch_op:
        batch_op.add_column(sa.Column('form_description', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('registration_links', schema=None) as batch_op:
        batch_op.drop_column('form_description')

    with op.batch_alter_table('churches', schema=None) as batch_op:
        batch_op.drop_constraint('church_name_district_area_camp_id_unique', type_='unique')

    # ### end Alembic commands ###
