"""update_uniqueconstraintupdate

Revision ID: 512eeff0d274
Revises: fa85fbf47d0f
Create Date: 2025-09-12 11:07:11.329941

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '512eeff0d274'
down_revision = 'fa85fbf47d0f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('financial_transactions', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_reference_camp', ['reference_number', 'camp_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('financial_transactions', schema=None) as batch_op:
        batch_op.drop_constraint('uq_reference_camp', type_='unique')

    # ### end Alembic commands ###
