"""update_detailstoPurchase

Revision ID: 527fe40f7d5c
Revises: 0f5c3c84dbd8
Create Date: 2025-09-30 21:04:14.950250

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '527fe40f7d5c'
down_revision = '0f5c3c84dbd8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('purchases', schema=None) as batch_op:
        batch_op.add_column(sa.Column('camper_name', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('is_item_supplied', sa.Boolean(), nullable=True, default=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('purchases', schema=None) as batch_op:
        batch_op.drop_column('is_item_supplied')
        batch_op.drop_column('camper_name')

    # ### end Alembic commands ###
