"""add_roomandfood

Revision ID: 85d323a03768
Revises: 512eeff0d274
Create Date: 2025-09-12 14:45:40.174282

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = '85d323a03768'
down_revision = '512eeff0d274'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('foods',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('vendor', sa.String(length=100), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('camp_id', sa.String(length=36), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['camp_id'], ['camps.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rooms',
    sa.Column('hostel_name', sa.String(length=100), nullable=False),
    sa.Column('block', sa.String(length=50), nullable=True),
    sa.Column('room_number', sa.String(length=20), nullable=False),
    sa.Column('room_capacity', sa.Integer(), nullable=True),
    sa.Column('is_special_room', sa.Boolean(), nullable=True),
    sa.Column('extra_beds', sa.Integer(), nullable=True),
    sa.Column('room_gender', sa.String(length=10), nullable=False),
    sa.Column('is_damaged', sa.Boolean(), nullable=True),
    sa.Column('misc_info', sa.Text(), nullable=True),
    sa.Column('camp_id', sa.String(length=36), nullable=False),
    sa.Column('adjoining_to', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['camp_id'], ['camps.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('hostel_name', 'block', 'room_number', 'camp_id', name='uq_room_number_camp')
    )
    op.create_table('food_allocations',
    sa.Column('food_id', sa.String(length=36), nullable=False),
    sa.Column('registration_id', sa.String(length=36), nullable=False),
    sa.Column('camp_id', sa.String(length=36), nullable=False),
    sa.Column('allocated_by', sa.String(length=36), nullable=False),
    sa.Column('allocation_date', sa.DateTime(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['allocated_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['camp_id'], ['camps.id'], ),
    sa.ForeignKeyConstraint(['food_id'], ['foods.id'], ),
    sa.ForeignKeyConstraint(['registration_id'], ['registrations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('room_allocations',
    sa.Column('room_id', sa.String(length=36), nullable=False),
    sa.Column('registration_id', sa.String(length=36), nullable=False),
    sa.Column('camp_id', sa.String(length=36), nullable=False),
    sa.Column('allocated_by', sa.String(length=36), nullable=False),
    sa.Column('allocation_date', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['allocated_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['camp_id'], ['camps.id'], ),
    sa.ForeignKeyConstraint(['registration_id'], ['registrations.id'], ),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('registration_id', 'camp_id', name='uq_registration_camp_allocation')
    )
    op.drop_table('_alembic_tmp_registrations')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('_alembic_tmp_registrations',
    sa.Column('surname', sa.VARCHAR(length=255), nullable=False),
    sa.Column('middle_name', sa.VARCHAR(length=255), nullable=True),
    sa.Column('last_name', sa.VARCHAR(length=255), nullable=False),
    sa.Column('age', sa.INTEGER(), nullable=False),
    sa.Column('email', sa.VARCHAR(length=255), nullable=True),
    sa.Column('phone_number', sa.VARCHAR(length=20), nullable=False),
    sa.Column('emergency_contact_name', sa.VARCHAR(length=255), nullable=False),
    sa.Column('emergency_contact_phone', sa.VARCHAR(length=20), nullable=False),
    sa.Column('church_id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('category_id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('custom_field_responses', sqlite.JSON(), nullable=True),
    sa.Column('total_amount', sa.NUMERIC(precision=10, scale=2), nullable=False),
    sa.Column('has_paid', sa.BOOLEAN(), nullable=False),
    sa.Column('has_checked_in', sa.BOOLEAN(), nullable=False),
    sa.Column('camp_id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('camper_code', sa.VARCHAR(length=10), nullable=True),
    sa.Column('registration_link_id', sa.VARCHAR(length=36), nullable=True),
    sa.Column('registration_date', sa.DATETIME(), nullable=False),
    sa.Column('id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.Column('sex', sa.VARCHAR(length=6), server_default=sa.text("'other'"), nullable=False),
    sa.Column('otp_code', sa.VARCHAR(length=6), nullable=True),
    sa.Column('otp_requested', sa.BOOLEAN(), nullable=False),
    sa.ForeignKeyConstraint(['camp_id'], ['camps.id'], ),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['church_id'], ['churches.id'], ),
    sa.ForeignKeyConstraint(['registration_link_id'], ['registration_links.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email', 'phone_number', 'camp_id', name=op.f('registration_email_phone_camp_unique'))
    )
    op.drop_table('room_allocations')
    op.drop_table('food_allocations')
    op.drop_table('rooms')
    op.drop_table('foods')
    # ### end Alembic commands ###
