"""add_financialModel

Revision ID: 89acd351c147
Revises: d82065349394
Create Date: 2025-09-06 19:46:17.429946

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '89acd351c147'
down_revision = 'd82065349394'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('financial_transactions',
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('received_by', sa.String(length=100), nullable=False),
    sa.Column('transaction_type', sa.String(length=20), nullable=False),
    sa.Column('transaction_category', sa.String(length=50), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('reference_number', sa.String(length=50), nullable=True),
    sa.Column('payment_method', sa.String(length=20), nullable=True),
    sa.Column('approved_by', sa.String(length=100), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('camp_id', sa.String(length=36), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['camp_id'], ['camps.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('reference_number')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('financial_transactions')
    # ### end Alembic commands ###
