"""create_payments

Revision ID: b07cc90a6c81
Revises: b562201d5e7a
Create Date: 2025-08-21 22:43:10.234307

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b07cc90a6c81'
down_revision = 'b562201d5e7a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payments',
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('payment_date', sa.DateTime(), nullable=False),
    sa.Column('payment_channel', sa.Enum('momo', 'cash', 'cheque', 'bank_transfer', 'card', name='payment_channel'), nullable=False),
    sa.Column('recorded_by', sa.String(length=36), nullable=False),
    sa.Column('payment_reference', sa.String(length=100), nullable=True),
    sa.Column('payment_metadata', sa.JSON(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['recorded_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('registration_payments',
    sa.Column('registration_id', sa.String(length=36), nullable=False),
    sa.Column('payment_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.id'], ),
    sa.ForeignKeyConstraint(['registration_id'], ['registrations.id'], ),
    sa.PrimaryKeyConstraint('registration_id', 'payment_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('registration_payments')
    op.drop_table('payments')
    # ### end Alembic commands ###
