"""nigeladdedsex

Revision ID: b562201d5e7a
Revises: 429a09c34ba2
Create Date: 2025-08-18 13:45:23.234491

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b562201d5e7a'
down_revision = '429a09c34ba2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('registrations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sex', sa.Enum('male', 'female', 'other', name='sex'), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('registrations', schema=None) as batch_op:
        batch_op.drop_column('sex')

    # ### end Alembic commands ###
