"""update_permissionstousers

Revision ID: bae253e116ab
Revises: c39dbf8c1a55
Create Date: 2025-09-12 20:37:56.118524

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bae253e116ab'
down_revision = 'c39dbf8c1a55'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('permissions', sa.JSON(), nullable=False, server_default=[]))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('permissions')

    # ### end Alembic commands ###
