"""create_addInventoryAndPurchases

Revision ID: bb6031bcd66f
Revises: 89acd351c147
Create Date: 2025-09-06 22:57:58.106924

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb6031bcd66f'
down_revision = '89acd351c147'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inventory',
    sa.Column('cost', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('inventory_type', sa.String(length=20), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('camp_id', sa.String(length=36), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['camp_id'], ['camps.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('purchases',
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('purchase_date', sa.DateTime(), nullable=False),
    sa.Column('camp_id', sa.String(length=36), nullable=False),
    sa.Column('inventory_ids', sa.String(length=100), nullable=False),
    sa.Column('sold_by', sa.String(length=36), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['camp_id'], ['camps.id'], ),
    sa.ForeignKeyConstraint(['sold_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pledges',
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('pledge_date', sa.DateTime(), nullable=False),
    sa.Column('camp_id', sa.String(length=36), nullable=False),
    sa.Column('camper_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['camp_id'], ['camps.id'], ),
    sa.ForeignKeyConstraint(['camper_id'], ['registrations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pledges')
    op.drop_table('purchases')
    op.drop_table('inventory')
    # ### end Alembic commands ###
