"""update_roomallocationupdate

Revision ID: c39dbf8c1a55
Revises: add_performance_indexes
Create Date: 2025-09-12 16:34:33.474524

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c39dbf8c1a55'
down_revision = 'add_performance_indexes'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('camp_workers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_camp_workers_camp_id'))
        batch_op.drop_index(batch_op.f('idx_camp_workers_role'))
        batch_op.drop_index(batch_op.f('idx_camp_workers_user_camp'))
        batch_op.drop_index(batch_op.f('idx_camp_workers_user_id'))

    with op.batch_alter_table('camps', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_camps_end_date'))
        batch_op.drop_index(batch_op.f('idx_camps_is_active'))
        batch_op.drop_index(batch_op.f('idx_camps_registration_deadline'))
        batch_op.drop_index(batch_op.f('idx_camps_start_date'))

    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_categories_camp_id'))
        batch_op.drop_index(batch_op.f('idx_categories_is_default'))
        batch_op.drop_index(batch_op.f('idx_categories_name'))

    with op.batch_alter_table('churches', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_churches_area'))
        batch_op.drop_index(batch_op.f('idx_churches_camp_id'))
        batch_op.drop_index(batch_op.f('idx_churches_district'))
        batch_op.drop_index(batch_op.f('idx_churches_name'))

    with op.batch_alter_table('custom_fields', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_custom_fields_camp_id'))
        batch_op.drop_index(batch_op.f('idx_custom_fields_field_type'))
        batch_op.drop_index(batch_op.f('idx_custom_fields_order'))

    with op.batch_alter_table('financial_transactions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_financial_camp_category'))
        batch_op.drop_index(batch_op.f('idx_financial_camp_deleted'))
        batch_op.drop_index(batch_op.f('idx_financial_camp_type'))
        batch_op.drop_index(batch_op.f('idx_financial_transactions_camp_id'))
        batch_op.drop_index(batch_op.f('idx_financial_transactions_date'))
        batch_op.drop_index(batch_op.f('idx_financial_transactions_is_deleted'))
        batch_op.drop_index(batch_op.f('idx_financial_transactions_payment_method'))
        batch_op.drop_index(batch_op.f('idx_financial_transactions_reference_number'))
        batch_op.drop_index(batch_op.f('idx_financial_transactions_transaction_category'))
        batch_op.drop_index(batch_op.f('idx_financial_transactions_transaction_type'))

    with op.batch_alter_table('food_allocations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_food_allocations_allocated_by'))
        batch_op.drop_index(batch_op.f('idx_food_allocations_allocation_date'))
        batch_op.drop_index(batch_op.f('idx_food_allocations_camp_id'))
        batch_op.drop_index(batch_op.f('idx_food_allocations_food_id'))
        batch_op.drop_index(batch_op.f('idx_food_allocations_registration_id'))

    with op.batch_alter_table('foods', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_foods_camp_category'))
        batch_op.drop_index(batch_op.f('idx_foods_camp_date'))
        batch_op.drop_index(batch_op.f('idx_foods_camp_id'))
        batch_op.drop_index(batch_op.f('idx_foods_category'))
        batch_op.drop_index(batch_op.f('idx_foods_date'))
        batch_op.drop_index(batch_op.f('idx_foods_vendor'))

    with op.batch_alter_table('inventory', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_inventory_camp_deleted'))
        batch_op.drop_index(batch_op.f('idx_inventory_camp_id'))
        batch_op.drop_index(batch_op.f('idx_inventory_inventory_type'))
        batch_op.drop_index(batch_op.f('idx_inventory_is_deleted'))

    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_payments_camp_id'))
        batch_op.drop_index(batch_op.f('idx_payments_payment_channel'))
        batch_op.drop_index(batch_op.f('idx_payments_payment_date'))
        batch_op.drop_index(batch_op.f('idx_payments_payment_reference'))
        batch_op.drop_index(batch_op.f('idx_payments_recorded_by'))

    with op.batch_alter_table('pledges', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_pledges_camp_id'))
        batch_op.drop_index(batch_op.f('idx_pledges_camper_camp'))
        batch_op.drop_index(batch_op.f('idx_pledges_camper_id'))
        batch_op.drop_index(batch_op.f('idx_pledges_pledge_date'))
        batch_op.drop_index(batch_op.f('idx_pledges_status'))

    with op.batch_alter_table('purchases', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_purchases_camp_id'))
        batch_op.drop_index(batch_op.f('idx_purchases_purchase_date'))
        batch_op.drop_index(batch_op.f('idx_purchases_sold_by'))

    with op.batch_alter_table('registration_links', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_registration_links_camp_id'))
        batch_op.drop_index(batch_op.f('idx_registration_links_created_by'))
        batch_op.drop_index(batch_op.f('idx_registration_links_expires_at'))
        batch_op.drop_index(batch_op.f('idx_registration_links_is_active'))
        batch_op.drop_index(batch_op.f('idx_registration_links_link_token'))

    with op.batch_alter_table('registration_payments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_registration_payments_created_at'))
        batch_op.drop_index(batch_op.f('idx_registration_payments_payment_id'))
        batch_op.drop_index(batch_op.f('idx_registration_payments_registration_id'))

    with op.batch_alter_table('registrations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_registrations_camp_category'))
        batch_op.drop_index(batch_op.f('idx_registrations_camp_checkin'))
        batch_op.drop_index(batch_op.f('idx_registrations_camp_church'))
        batch_op.drop_index(batch_op.f('idx_registrations_camp_paid'))
        batch_op.drop_index(batch_op.f('idx_registrations_camper_code'))
        batch_op.drop_index(batch_op.f('idx_registrations_category_id'))
        batch_op.drop_index(batch_op.f('idx_registrations_church_id'))
        batch_op.drop_index(batch_op.f('idx_registrations_email'))
        batch_op.drop_index(batch_op.f('idx_registrations_email_phone_camp'))
        batch_op.drop_index(batch_op.f('idx_registrations_has_checked_in'))
        batch_op.drop_index(batch_op.f('idx_registrations_has_paid'))
        batch_op.drop_index(batch_op.f('idx_registrations_otp_requested'))
        batch_op.drop_index(batch_op.f('idx_registrations_phone_number'))
        batch_op.drop_index(batch_op.f('idx_registrations_registration_date'))
        batch_op.drop_index(batch_op.f('idx_registrations_registration_link_id'))
        batch_op.drop_index(batch_op.f('idx_registrations_sex'))

    with op.batch_alter_table('room_allocations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_room_allocations_allocated_by'))
        batch_op.drop_index(batch_op.f('idx_room_allocations_allocation_date'))
        batch_op.drop_index(batch_op.f('idx_room_allocations_camp_active'))
        batch_op.drop_index(batch_op.f('idx_room_allocations_camp_id'))
        batch_op.drop_index(batch_op.f('idx_room_allocations_is_active'))
        batch_op.drop_index(batch_op.f('idx_room_allocations_registration_id'))
        batch_op.drop_index(batch_op.f('idx_room_allocations_room_id'))
        batch_op.drop_constraint(batch_op.f('uq_registration_camp_allocation'), type_='unique')
        batch_op.create_unique_constraint('uq_registration_camp_allocation', ['registration_id', 'camp_id', 'is_active'])

    with op.batch_alter_table('rooms', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_rooms_camp_damaged'))
        batch_op.drop_index(batch_op.f('idx_rooms_camp_gender'))
        batch_op.drop_index(batch_op.f('idx_rooms_camp_id'))
        batch_op.drop_index(batch_op.f('idx_rooms_hostel_name'))
        batch_op.drop_index(batch_op.f('idx_rooms_is_damaged'))
        batch_op.drop_index(batch_op.f('idx_rooms_is_special_room'))
        batch_op.drop_index(batch_op.f('idx_rooms_room_gender'))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_users_email'))
        batch_op.drop_index(batch_op.f('idx_users_role'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_users_role'), ['role'], unique=False)
        batch_op.create_index(batch_op.f('idx_users_email'), ['email'], unique=False)

    with op.batch_alter_table('rooms', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_rooms_room_gender'), ['room_gender'], unique=False)
        batch_op.create_index(batch_op.f('idx_rooms_is_special_room'), ['is_special_room'], unique=False)
        batch_op.create_index(batch_op.f('idx_rooms_is_damaged'), ['is_damaged'], unique=False)
        batch_op.create_index(batch_op.f('idx_rooms_hostel_name'), ['hostel_name'], unique=False)
        batch_op.create_index(batch_op.f('idx_rooms_camp_id'), ['camp_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_rooms_camp_gender'), ['camp_id', 'room_gender'], unique=False)
        batch_op.create_index(batch_op.f('idx_rooms_camp_damaged'), ['camp_id', 'is_damaged'], unique=False)

    with op.batch_alter_table('room_allocations', schema=None) as batch_op:
        batch_op.drop_constraint('uq_registration_camp_allocation', type_='unique')
        batch_op.create_unique_constraint(batch_op.f('uq_registration_camp_allocation'), ['registration_id', 'camp_id'])
        batch_op.create_index(batch_op.f('idx_room_allocations_room_id'), ['room_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_room_allocations_registration_id'), ['registration_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_room_allocations_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('idx_room_allocations_camp_id'), ['camp_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_room_allocations_camp_active'), ['camp_id', 'is_active'], unique=False)
        batch_op.create_index(batch_op.f('idx_room_allocations_allocation_date'), ['allocation_date'], unique=False)
        batch_op.create_index(batch_op.f('idx_room_allocations_allocated_by'), ['allocated_by'], unique=False)

    with op.batch_alter_table('registrations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_registrations_sex'), ['sex'], unique=False)
        batch_op.create_index(batch_op.f('idx_registrations_registration_link_id'), ['registration_link_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_registrations_registration_date'), ['registration_date'], unique=False)
        batch_op.create_index(batch_op.f('idx_registrations_phone_number'), ['phone_number'], unique=False)
        batch_op.create_index(batch_op.f('idx_registrations_otp_requested'), ['otp_requested'], unique=False)
        batch_op.create_index(batch_op.f('idx_registrations_has_paid'), ['has_paid'], unique=False)
        batch_op.create_index(batch_op.f('idx_registrations_has_checked_in'), ['has_checked_in'], unique=False)
        batch_op.create_index(batch_op.f('idx_registrations_email_phone_camp'), ['email', 'phone_number', 'camp_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_registrations_email'), ['email'], unique=False)
        batch_op.create_index(batch_op.f('idx_registrations_church_id'), ['church_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_registrations_category_id'), ['category_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_registrations_camper_code'), ['camper_code'], unique=False)
        batch_op.create_index(batch_op.f('idx_registrations_camp_paid'), ['camp_id', 'has_paid'], unique=False)
        batch_op.create_index(batch_op.f('idx_registrations_camp_church'), ['camp_id', 'church_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_registrations_camp_checkin'), ['camp_id', 'has_checked_in'], unique=False)
        batch_op.create_index(batch_op.f('idx_registrations_camp_category'), ['camp_id', 'category_id'], unique=False)

    with op.batch_alter_table('registration_payments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_registration_payments_registration_id'), ['registration_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_registration_payments_payment_id'), ['payment_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_registration_payments_created_at'), ['created_at'], unique=False)

    with op.batch_alter_table('registration_links', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_registration_links_link_token'), ['link_token'], unique=False)
        batch_op.create_index(batch_op.f('idx_registration_links_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('idx_registration_links_expires_at'), ['expires_at'], unique=False)
        batch_op.create_index(batch_op.f('idx_registration_links_created_by'), ['created_by'], unique=False)
        batch_op.create_index(batch_op.f('idx_registration_links_camp_id'), ['camp_id'], unique=False)

    with op.batch_alter_table('purchases', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_purchases_sold_by'), ['sold_by'], unique=False)
        batch_op.create_index(batch_op.f('idx_purchases_purchase_date'), ['purchase_date'], unique=False)
        batch_op.create_index(batch_op.f('idx_purchases_camp_id'), ['camp_id'], unique=False)

    with op.batch_alter_table('pledges', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_pledges_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('idx_pledges_pledge_date'), ['pledge_date'], unique=False)
        batch_op.create_index(batch_op.f('idx_pledges_camper_id'), ['camper_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_pledges_camper_camp'), ['camper_id', 'camp_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_pledges_camp_id'), ['camp_id'], unique=False)

    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_payments_recorded_by'), ['recorded_by'], unique=False)
        batch_op.create_index(batch_op.f('idx_payments_payment_reference'), ['payment_reference'], unique=False)
        batch_op.create_index(batch_op.f('idx_payments_payment_date'), ['payment_date'], unique=False)
        batch_op.create_index(batch_op.f('idx_payments_payment_channel'), ['payment_channel'], unique=False)
        batch_op.create_index(batch_op.f('idx_payments_camp_id'), ['camp_id'], unique=False)

    with op.batch_alter_table('inventory', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_inventory_is_deleted'), ['is_deleted'], unique=False)
        batch_op.create_index(batch_op.f('idx_inventory_inventory_type'), ['inventory_type'], unique=False)
        batch_op.create_index(batch_op.f('idx_inventory_camp_id'), ['camp_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_inventory_camp_deleted'), ['camp_id', 'is_deleted'], unique=False)

    with op.batch_alter_table('foods', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_foods_vendor'), ['vendor'], unique=False)
        batch_op.create_index(batch_op.f('idx_foods_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('idx_foods_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('idx_foods_camp_id'), ['camp_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_foods_camp_date'), ['camp_id', 'date'], unique=False)
        batch_op.create_index(batch_op.f('idx_foods_camp_category'), ['camp_id', 'category'], unique=False)

    with op.batch_alter_table('food_allocations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_food_allocations_registration_id'), ['registration_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_food_allocations_food_id'), ['food_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_food_allocations_camp_id'), ['camp_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_food_allocations_allocation_date'), ['allocation_date'], unique=False)
        batch_op.create_index(batch_op.f('idx_food_allocations_allocated_by'), ['allocated_by'], unique=False)

    with op.batch_alter_table('financial_transactions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_financial_transactions_transaction_type'), ['transaction_type'], unique=False)
        batch_op.create_index(batch_op.f('idx_financial_transactions_transaction_category'), ['transaction_category'], unique=False)
        batch_op.create_index(batch_op.f('idx_financial_transactions_reference_number'), ['reference_number'], unique=False)
        batch_op.create_index(batch_op.f('idx_financial_transactions_payment_method'), ['payment_method'], unique=False)
        batch_op.create_index(batch_op.f('idx_financial_transactions_is_deleted'), ['is_deleted'], unique=False)
        batch_op.create_index(batch_op.f('idx_financial_transactions_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('idx_financial_transactions_camp_id'), ['camp_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_financial_camp_type'), ['camp_id', 'transaction_type'], unique=False)
        batch_op.create_index(batch_op.f('idx_financial_camp_deleted'), ['camp_id', 'is_deleted'], unique=False)
        batch_op.create_index(batch_op.f('idx_financial_camp_category'), ['camp_id', 'transaction_category'], unique=False)

    with op.batch_alter_table('custom_fields', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_custom_fields_order'), ['order'], unique=False)
        batch_op.create_index(batch_op.f('idx_custom_fields_field_type'), ['field_type'], unique=False)
        batch_op.create_index(batch_op.f('idx_custom_fields_camp_id'), ['camp_id'], unique=False)

    with op.batch_alter_table('churches', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_churches_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('idx_churches_district'), ['district'], unique=False)
        batch_op.create_index(batch_op.f('idx_churches_camp_id'), ['camp_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_churches_area'), ['area'], unique=False)

    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_categories_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('idx_categories_is_default'), ['is_default'], unique=False)
        batch_op.create_index(batch_op.f('idx_categories_camp_id'), ['camp_id'], unique=False)

    with op.batch_alter_table('camps', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_camps_start_date'), ['start_date'], unique=False)
        batch_op.create_index(batch_op.f('idx_camps_registration_deadline'), ['registration_deadline'], unique=False)
        batch_op.create_index(batch_op.f('idx_camps_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('idx_camps_end_date'), ['end_date'], unique=False)

    with op.batch_alter_table('camp_workers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_camp_workers_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_camp_workers_user_camp'), ['user_id', 'camp_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_camp_workers_role'), ['role'], unique=False)
        batch_op.create_index(batch_op.f('idx_camp_workers_camp_id'), ['camp_id'], unique=False)

    # ### end Alembic commands ###
