"""otp and otp_code

Revision ID: d82065349394
Revises: 42194705610f
Create Date: 2025-09-02 14:40:31.323115

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd82065349394'
down_revision = '42194705610f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('registrations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('otp_code', sa.String(length=6), nullable=True))
        batch_op.add_column(sa.Column('otp_requested', sa.Boolean(), nullable=False, default=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('registrations', schema=None) as batch_op:
        batch_op.drop_column('otp_requested')
        batch_op.drop_column('otp_code')

    # ### end Alembic commands ###
