"""update_pledgesPartial

Revision ID: e3e31d3b1969
Revises: 527fe40f7d5c
Create Date: 2025-10-16 13:34:08.527921

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e3e31d3b1969'
down_revision = '527fe40f7d5c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    try:
        op.create_table('pledge_fulfillments',
        sa.Column('pledge_id', sa.String(length=36), nullable=False),
        sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column('fulfillment_date', sa.DateTime(), nullable=False),
        sa.Column('payment_method', sa.Enum('momo', 'cash', 'cheque', 'bank_transfer', 'card', name='fulfillment_payment_method'), nullable=False),
        sa.Column('recorded_by', sa.String(length=36), nullable=False),
        sa.Column('reference_number', sa.String(length=100), nullable=True),
        sa.Column('notes', sa.Text(), nullable=True),
        sa.Column('camp_id', sa.String(length=36), nullable=False),
        sa.Column('id', sa.String(length=36), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(['camp_id'], ['camps.id'], ),
        sa.ForeignKeyConstraint(['pledge_id'], ['pledges.id'], ),
        sa.ForeignKeyConstraint(['recorded_by'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id')
        )
    except:
        pass  # Table might already exist
    with op.batch_alter_table('pledges', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fulfilled_amount', sa.Numeric(precision=10, scale=2), nullable=True, server_default='0.00', default=0.00))
        batch_op.add_column(sa.Column('notes', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pledges', schema=None) as batch_op:
        batch_op.drop_column('notes')
        batch_op.drop_column('fulfilled_amount')

    op.drop_table('pledge_fulfillments')
    # ### end Alembic commands ###
