"""update_inventoryAndPurchases

Revision ID: fa85fbf47d0f
Revises: bb6031bcd66f
Create Date: 2025-09-06 23:23:10.974235

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa85fbf47d0f'
down_revision = 'bb6031bcd66f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('purchases', schema=None) as batch_op:
        batch_op.add_column(sa.Column('items', sa.JSON(), nullable=False))
        batch_op.alter_column('inventory_ids',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('purchases', schema=None) as batch_op:
        batch_op.alter_column('inventory_ids',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.drop_column('items')

    # ### end Alembic commands ###
